config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'

  authenticate :user, lambda { |u| u.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  apipie
  # devise_for :users, ActiveAdmin::Devise.config
  devise_for :users, {
      path: ActiveAdmin.application.default_namespace || "/",
      controllers: {
          passwords: "active_admin/devise/passwords",
          confirmations: 'active_admin/devise/confirmations',
          sessions: "active_admin/devise/sessions"
      },
      path_names: {sign_in: 'login', sign_out: "logout"},
      sign_out_via: [*::Devise.sign_out_via, ActiveAdmin.application.logout_link_method].uniq
  }
  devise_for :project_managers , {
      path: :pm,
      controllers: {
          passwords: "active_admin/devise/passwords",
          confirmations: 'active_admin/devise/confirmations',
          sessions: "active_admin/devise/sessions"
      },
      path_names: { sign_in: 'login', sign_out: "logout"},
      sign_out_via: [*::Devise.sign_out_via, ActiveAdmin.application.logout_link_method].uniq
  }
  namespace :api, defaults: {format: 'json'} do
     namespace :v1 do
       mount_devise_token_auth_for 'User', at: 'auth', :controllers => {  sessions: "api/v1/users/sessions"}
       mount_devise_token_auth_for 'LandManager', at: 'auth', :controllers => { registrations: "api/v1/users/registrations"}
       resources :conversations, only: [:index, :create, :destroy] do
         resources :messages, only: [:index, :create, :update, :destroy]
         get :participants
         put :add_participants
       end
       resources :land_managers, only: [:show, :update, :index]
       resources :project_managers, only: [:show, :update]
       resources :blocked_users, only: [:index, :create, :show]
       delete 'un_blocked_user' => 'blocked_users#destroy'
       get 'eula/latest' => 'eulas#latest'
       get 'privacy/latest' => 'privacies#latest'
       resources :ratings, only: [:show, :create, :update]
       resources :feedbacks, only: [:show, :create]
       resources :reported_ratings, only: [:show, :create]
       resources :reported_chats, only: [:show, :create]
       resources :jobs
       resources :notifications, only: [:index, :destroy]
       delete 'notifications' => 'notifications#destroy_all'
       resources :tutorials
       resources :pages do
         collection do
           get :about
         end
       end
       resources :documents
       resources :categories
       resources :sub_categories, only: [:index]
       resources :submissions, only: [:create, :show]
       resources :projects, only: [:index, :species, :leave] do
         get :species
         collection do
           post :leave
           post :join
         end
       end
     end
   end
  ActiveAdmin.routes(self)
  devise_scope :user do
    get '/land_manager/confirmation', to: 'users/confirmations#show', as: :land_manager_confirmation
    get '/land_manager_confirmed', to: 'users#land_manager_confirmed', as: :land_manager_confirmed
  end

  scope :pm, :controller => 'invitations'  do
    get 'accept_invitation', as: :pm_accept_invitation
    get 'reject_invitation', as: :pm_reject_invitation
    post 'accept', as: :pm_accept
  end


  root 'admin/dashboard#index'
  resources :users
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  layout 'layouts/active_admin_logged_out'

  def accept_invitation
    if params[:token]
      token, project, user = Base64.urlsafe_decode64(params[:token]).split('_')
      @user = User.find(user)
      @user = ProjectManager.find(user) if @user.project_manager?
      pmp = ProjectManagerProject.where(project_id: project, project_manager_id: user, token: token).first
      if pmp.present?
        pmp.update_attributes!(status: 'accepted')
        @project = Project.find(project)
      end
      if @user.pm_invited? && !@user.confirmed?
        if @user.save
          render 'invitations/accept_invitation', :user => @user
        end
      elsif @user.land_manager?
        if pmp.is_admin
          @user.update_attributes!(user_type: 'project_manager')
          redirect_to pm_root_path
        else
          render 'invitations/lm_no_admin_accept_invitation', @project => @project
        end
      else
        flash[:error] = 'Please login, you are already part of the system'
        redirect_to pm_root_path
      end
    else
      render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
    end
  end

  def accept
    params[:project_manager] = params[:project_manager].merge(confirmed_at: Time.current, approved: true, pm_invited: false)
    if params[:project_manager].present?
      user = User.find(params[:user])
      if params[:project_manager][:password] == params[:project_manager][:password_confirmation]
        permitted = params.require(:project_manager).permit(:email, :password, :password_confirmation, :confirmed_at, :approved, :pm_invited)
        user.update!(permitted)
        sign_in user
        redirect_to pm_projects_path
      end
    else
    end
  end

  def reject_invitation
    if params[:token]
      token, project, user = Base64.urlsafe_decode64(params[:token]).split('_')
      @user = User.find(user)
      pmp = ProjectManagerProject.where(project_id: project, project_manager_id: user, token: token).first
      if pmp.present?
        pmp.update_attributes!(status: 'rejected')
        @project = Project.find(project)
      end
    else
      render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
    end
  end


end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/accept_invitation.html.erb
<h2><%= "You have been invited as a project manager to #{@project&.title}" %></h2>
  <%= form_for(@user, :url => pm_accept_path(user: @user), method: :post) do |f| %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, readonly: true %>
    </div>
    <br>
    <div class="field">
      <%= f.label :password %>
      <em>(8 characters minimum)</em>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>
    <br>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Accept Invitation" %>
  </div>
<% end %>

<script>
  $(document).ready(() => {
    $("form").submit(function(e){
        console.log('done !!')
      if(($('#project_manager_password').val().trim() == $('#project_manager_password_confirmation').val().trim()) && ($('#project_manager_password').val().trim().length == 8)) {
          console.log('password passed!!')
          return true;      }
      else {
        alert('Password must be same and of minimum 8 digits.');
        return false;;
      }
    });
  });
</script>

app/views/invitations/lm_no_admin_accept_invitation.html.erb
<h2>Accept Invitation.</h2>
<p><%= "You have accepted project invitation to #{@project&.title}" %></p>

app/views/invitations/reject_invitation.html.erb
<h2>Reject Invitation.</h2>
<p><%= "You have rejected project invitation to #{@project&.title}" %></p>